# -*- coding: utf-8 -*-
"""formatted_notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jV5ya3T4GeE3TJoljRj8sv4CwIl8kkgH

# FORMATTED ZONE

##### Steps to access to the DB store in my local host:
"""

#!pip install psycopg2
#!pip install pandas

"""https://research.google.com/colaboratory/intl/en-GB/local-runtimes.html

<b>1. Create a virtual env (en cmd)</b>
- C:\Users\Andrea> pip install virtualenv
- C:\Users\Andrea> python3 -m venv env
- C:\Users\Andrea> cd C:\Users\Andrea\env\Scripts
- C:\Users\Andrea> activate.bat

<b>2. Connect to local runtime</b>
- (env) C:\Users\Andrea\env> pip install jupyter
- (env) C:\Users\Andrea\env> pip install jupyter_http_over_ws
- (env) C:\Users\Andrea\env> jupyter serverextension enable --py jupyter_http_over_ws
- (env) C:\Users\Andrea\env> jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --port=8888 --NotebookApp.port_retries=0

<b>3. In Google Colab (do not close cmd)</b>
- In the right, next to 'Editar', open the tab <u>Conectar a un entorno de ejecución local</u>
- Copy from the cmd <i>http://localhost:8888/?token=8dhfyd</i> and connect.

## Installs and imports
"""

#!pip install psycopg2
#!pip install pandas

import psycopg2
from psycopg2 import Error
import pandas as pd

"""## Get the data from the database in PostgreSQL"""

dataframe_barcelona = ["\"2011_atur_per_sexe_csv\"", "\"2012_atur_per_sexe_csv\"", "\"2013_atur_per_sexe_csv\"", "\"2014_atur_per_sexe_csv\"", 
                  "\"2015_atur_per_sexe_csv\"", "\"2016_atur_per_sexe_csv\"", "\"2017_atur_per_sexe_csv\"", "\"2018_atur_per_sexe_csv\"" ,
                  "\"2019_atur_per_sexe_csv\"", "\"2020_atur_per_sexe_csv\"", "\"2021_atur_per_sexe_csv\""]


try:
    connection = psycopg2.connect(user="adsdb",
                                  password="adsdb",
                                  host="localhost",
                                  port="5432",
                                  database="postgres")

    cursor = connection.cursor()
    for i in dataframe_barcelona:
      if i==dataframe_barcelona[0]:

        query = "select * from" + i
        cursor.execute(query)

        record = cursor.fetchall()
        df_atur_per_sexe = pd.DataFrame(record, columns=['Year', 'Month', 'Code_District', 
                                   'Name_Districte', 'Code_Neighborhood', 'Name_Neighborhood', 
                                   'Gender', 'Demmand_occupancy', 'Number'])
       
      else:
        df1 = df_atur_per_sexe
        query = "select * from" + i
        cursor.execute(query)
        record = cursor.fetchall()
        df_atur_per_sexe = pd.DataFrame(record, columns=['Year', 'Month', 'Code_District', 
                                   'Name_Districte', 'Code_Neighborhood', 'Name_Neighborhood', 
                                   'Gender', 'Demmand_occupancy', 'Number'])
        
        df_atur_per_sexe = pd.concat([df_atur_per_sexe, df1])
      
    cursor.execute("select * from export_ine_csv")
    record = cursor.fetchall()
    df_export_ine = pd.DataFrame(record, columns=['Gender', 'CCAA', 'Age', 'Quarter', 'Total'])

    cursor.execute("select * from export_ine_education_modificado_csv")
    record = cursor.fetchall()
    df_export_ine_education = pd.DataFrame(record, columns=['Gender', 'CCAA', 'Education_Sector', 'Year', 'Rate'])
    

except (Exception, Error) as error:
    print("Error while connecting to PostgreSQL", error)
finally:
    if (connection):
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

"""### Head of the data sets"""

df_atur_per_sexe.head()

df_export_ine.head()

df_export_ine_education.head()

"""## Save the results

We save the results in our local computer due to we can not connect this notebook to Google Drive. This datasets will be uploaded to the landing folder, into the `1. output formatted zone` folder.
"""

df_atur_per_sexe.to_csv('C:/Users/Andrea/atur_per_sexe.csv', encoding='utf-8')
df_export_ine.to_csv('C:/Users/Andrea/export_ine.csv', encoding='utf-8')
df_export_ine_education.to_csv('C:/Users/Andrea/df_export_ine_education.csv', encoding='utf-8')